# airports.py - Complete list of all civilian airports in India
INDIAN_AIRPORTS = {
    # International Airports (37)
    "VAAH": {"iata": "AMD", "name": "Sardar Vallabhbhai Patel International", "city": "Ahmedabad",
             "type": "International"},
    "VABB": {"iata": "BOM", "name": "Chhatrapati Shivaji Maharaj International", "city": "Mumbai",
             "type": "International"},
    "VABI": {"iata": "BHJ", "name": "Bhuj Airport", "city": "Bhuj", "type": "International"},
    "VABJ": {"iata": "BHO", "name": "Raja Bhoj Airport", "city": "Bhopal", "type": "International"},
    "VABO": {"iata": "BDQ", "name": "Vadodara Airport", "city": "Vadodara", "type": "International"},
    "VABP": {"iata": "BBI", "name": "Biju Patnaik International", "city": "Bhubaneswar", "type": "International"},
    "VAGO": {"iata": "GOI", "name": "Dabolim Airport", "city": "Goa", "type": "International"},
    "VAID": {"iata": "IDR", "name": "Devi Ahilya Bai Holkar Airport", "city": "Indore", "type": "International"},
    "VAJB": {"iata": "JLR", "name": "Jabalpur Airport", "city": "Jabalpur", "type": "International"},
    "VAJM": {"iata": "JGA", "name": "Jamnagar Airport", "city": "Jamnagar", "type": "International"},
    "VAKJ": {"iata": "HJR", "name": "Khajuraho Airport", "city": "Khajuraho", "type": "International"},
    "VANP": {"iata": "NAG", "name": "Dr. Babasaheb Ambedkar International", "city": "Nagpur", "type": "International"},
    "VAUD": {"iata": "UDR", "name": "Maharana Pratap Airport", "city": "Udaipur", "type": "International"},
    "VCBI": {"iata": "CMB", "name": "Bandaranaike International (Sri Lanka)", "city": "Colombo",
             "type": "International"},
    "VEAT": {"iata": "IXA", "name": "Agartala Airport", "city": "Agartala", "type": "International"},
    "VEBD": {"iata": "IXB", "name": "Bagdogra International", "city": "Siliguri", "type": "International"},
    "VEBG": {"iata": "RGH", "name": "Balurghat Airport", "city": "Balurghat", "type": "International"},
    "VECC": {"iata": "CCU", "name": "Netaji Subhas Chandra Bose International", "city": "Kolkata",
             "type": "International"},
    "VEGK": {"iata": "GAY", "name": "Gaya Airport", "city": "Gaya", "type": "International"},
    "VEGT": {"iata": "GAU", "name": "Lokpriya Gopinath Bordoloi International", "city": "Guwahati",
             "type": "International"},
    "VEIM": {"iata": "IMF", "name": "Imphal International", "city": "Imphal", "type": "International"},
    "VEJT": {"iata": "JRH", "name": "Jorhat Airport", "city": "Jorhat", "type": "International"},
    "VELR": {"iata": "IXI", "name": "Lilabari Airport", "city": "Lilabari", "type": "International"},
    "VEMN": {"iata": "AJL", "name": "Lengpui Airport", "city": "Aizawl", "type": "International"},
    "VEPG": {"iata": "IXT", "name": "Pasighat Airport", "city": "Pasighat", "type": "International"},
    "VEPT": {"iata": "PAT", "name": "Jay Prakash Narayan Airport", "city": "Patna", "type": "International"},
    "VERC": {"iata": "IXR", "name": "Birsa Munda Airport", "city": "Ranchi", "type": "International"},
    "VIAG": {"iata": "AGR", "name": "Agra Airport", "city": "Agra", "type": "International"},
    "VIAL": {"iata": "IXD", "name": "Allahabad Airport", "city": "Allahabad", "type": "International"},
    "VIAR": {"iata": "ATQ", "name": "Sri Guru Ram Dass Jee International", "city": "Amritsar", "type": "International"},
    "VIDP": {"iata": "DEL", "name": "Indira Gandhi International", "city": "Delhi", "type": "International"},
    "VIJO": {"iata": "JDH", "name": "Jodhpur Airport", "city": "Jodhpur", "type": "International"},
    "VIJP": {"iata": "JAI", "name": "Jaipur International", "city": "Jaipur", "type": "International"},
    "VIJU": {"iata": "IXJ", "name": "Jammu Airport", "city": "Jammu", "type": "International"},
    "VIKA": {"iata": "KNU", "name": "Kanpur Airport", "city": "Kanpur", "type": "International"},
    "VIKO": {"iata": "KTU", "name": "Kota Airport", "city": "Kota", "type": "International"},
    "VILK": {"iata": "LUH", "name": "Ludhiana Airport", "city": "Ludhiana", "type": "International"},
    "VIST": {"iata": "SXR", "name": "Sheikh ul-Alam International", "city": "Srinagar", "type": "International"},
    "VISR": {"iata": "IXS", "name": "Silchar Airport", "city": "Silchar", "type": "International"},
    "VISM": {"iata": "SLV", "name": "Shimla Airport", "city": "Shimla", "type": "International"},
    "VITE": {"iata": "TNI", "name": "Satna Airport", "city": "Satna", "type": "International"},
    "VIUD": {"iata": "UDR", "name": "Maharana Pratap Airport", "city": "Udaipur", "type": "International"},
    "VIVA": {"iata": "VNS", "name": "Lal Bahadur Shastri Airport", "city": "Varanasi", "type": "International"},
    "VOAT": {"iata": "AGX", "name": "Agatti Airport", "city": "Agatti Island", "type": "International"},
    "VOBG": {"iata": "BLR", "name": "Kempegowda International", "city": "Bengaluru", "type": "International"},
    "VOCI": {"iata": "COK", "name": "Cochin International", "city": "Kochi", "type": "International"},
    "VOCL": {"iata": "CCJ", "name": "Calicut International", "city": "Kozhikode", "type": "International"},
    "VOCP": {"iata": "CDP", "name": "Kadapa Airport", "city": "Kadapa", "type": "International"},
    "VOCB": {"iata": "CJB", "name": "Coimbatore International", "city": "Coimbatore", "type": "International"},
    "VOHY": {"iata": "HYD", "name": "Rajiv Gandhi International", "city": "Hyderabad", "type": "International"},
    "VOMD": {"iata": "IXM", "name": "Madurai Airport", "city": "Madurai", "type": "International"},
    "VOML": {"iata": "IXE", "name": "Mangalore International", "city": "Mangalore", "type": "International"},
    "VOMM": {"iata": "MAA", "name": "Chennai International", "city": "Chennai", "type": "International"},
    "VOPB": {"iata": "IXZ", "name": "Vir Savarkar International", "city": "Port Blair", "type": "International"},
    "VOPC": {"iata": "PNY", "name": "Pondicherry Airport", "city": "Puducherry", "type": "International"},
    "VORY": {"iata": "RJA", "name": "Rajahmundry Airport", "city": "Rajahmundry", "type": "International"},
    "VOTR": {"iata": "TIR", "name": "Tirupati Airport", "city": "Tirupati", "type": "International"},
    "VOTV": {"iata": "TRV", "name": "Trivandrum International", "city": "Thiruvananthapuram", "type": "International"},
    "VOVZ": {"iata": "VTZ", "name": "Visakhapatnam Airport", "city": "Visakhapatnam", "type": "International"},

    # Domestic Airports (100+)
    "VA1B": {"iata": "BEP", "name": "Bellary Airport", "city": "Bellary", "type": "Domestic"},
    "VA1J": {"iata": "PYB", "name": "Jeypore Airport", "city": "Jeypore", "type": "Domestic"},
    "VA1P": {"iata": "PAB", "name": "Bilaspur Airport", "city": "Bilaspur", "type": "Domestic"},
    "VAAK": {"iata": "AKD", "name": "Akola Airport", "city": "Akola", "type": "Domestic"},
    "VAAU": {"iata": "IXU", "name": "Aurangabad Airport", "city": "Aurangabad", "type": "Domestic"},
    "VABV": {"iata": "BHU", "name": "Bhavnagar Airport", "city": "Bhavnagar", "type": "Domestic"},
    "VADN": {"iata": "NMB", "name": "Daman Airport", "city": "Daman", "type": "Domestic"},
    "VADU": {"iata": "DIU", "name": "Diu Airport", "city": "Diu", "type": "Domestic"},
    "VAGB": {"iata": "GUX", "name": "Guna Airport", "city": "Guna", "type": "Domestic"},
    "VAJB": {"iata": "JLR", "name": "Jabalpur Airport", "city": "Jabalpur", "type": "Domestic"},
    "VAKD": {"iata": "KHD", "name": "Khandwa Airport", "city": "Khandwa", "type": "Domestic"},
    "VAKE": {"iata": "IXK", "name": "Keshod Airport", "city": "Keshod", "type": "Domestic"},
    "VAKJ": {"iata": "HJR", "name": "Khajuraho Airport", "city": "Khajuraho", "type": "Domestic"},
    "VAKP": {"iata": "KLH", "name": "Kolhapur Airport", "city": "Kolhapur", "type": "Domestic"},
    "VANR": {"iata": "ISK", "name": "Nashik Airport", "city": "Nashik", "type": "Domestic"},
    "VAOZ": {"iata": "OMN", "name": "Osmanabad Airport", "city": "Osmanabad", "type": "Domestic"},
    "VAPO": {"iata": "PNQ", "name": "Pune Airport", "city": "Pune", "type": "Domestic"},
    "VAPR": {"iata": "PBD", "name": "Porbandar Airport", "city": "Porbandar", "type": "Domestic"},
    "VARK": {"iata": "RAJ", "name": "Rajkot Airport", "city": "Rajkot", "type": "Domestic"},
    "VARP": {"iata": "RPR", "name": "Raipur Airport", "city": "Raipur", "type": "Domestic"},
    "VASD": {"iata": "SAG", "name": "Shirdi Airport", "city": "Shirdi", "type": "Domestic"},
    "VASL": {"iata": "SSE", "name": "Solapur Airport", "city": "Solapur", "type": "Domestic"},
    "VAUD": {"iata": "UDR", "name": "Maharana Pratap Airport", "city": "Udaipur", "type": "Domestic"},
    "VEAZ": {"iata": "AJL", "name": "Lengpui Airport", "city": "Aizawl", "type": "Domestic"},
    "VEBD": {"iata": "IXB", "name": "Bagdogra Airport", "city": "Siliguri", "type": "Domestic"},
    "VEBK": {"iata": "BKB", "name": "Bikaner Airport", "city": "Bikaner", "type": "Domestic"},
    "VEBS": {"iata": "BBI", "name": "Biju Patnaik Airport", "city": "Bhubaneswar", "type": "Domestic"},
    "VECK": {"iata": "COH", "name": "Cooch Behar Airport", "city": "Cooch Behar", "type": "Domestic"},
    "VEDG": {"iata": "RDP", "name": "Kazi Nazrul Islam Airport", "city": "Durgapur", "type": "Domestic"},
    "VEIM": {"iata": "IMF", "name": "Imphal Airport", "city": "Imphal", "type": "Domestic"},
    "VEJH": {"iata": "JRH", "name": "Jorhat Airport", "city": "Jorhat", "type": "Domestic"},
    "VEJS": {"iata": "IXW", "name": "Sonari Airport", "city": "Jamshedpur", "type": "Domestic"},
    "VEKU": {"iata": "IXS", "name": "Silchar Airport", "city": "Silchar", "type": "Domestic"},
    "VELP": {"iata": "AJL", "name": "Lengpui Airport", "city": "Aizawl", "type": "Domestic"},
    "VEMZ": {"iata": "MZU", "name": "Muzaffarpur Airport", "city": "Muzaffarpur", "type": "Domestic"},
    "VEPG": {"iata": "IXT", "name": "Pasighat Airport", "city": "Pasighat", "type": "Domestic"},
    "VEPH": {"iata": "PAT", "name": "Jay Prakash Narayan Airport", "city": "Patna", "type": "Domestic"},
    "VEPL": {"iata": "IXP", "name": "Pathankot Airport", "city": "Pathankot", "type": "Domestic"},
    "VEPT": {"iata": "PAT", "name": "Jay Prakash Narayan Airport", "city": "Patna", "type": "Domestic"},
    "VERC": {"iata": "IXR", "name": "Birsa Munda Airport", "city": "Ranchi", "type": "Domestic"},
    "VERK": {"iata": "RRK", "name": "Rourkela Airport", "city": "Rourkela", "type": "Domestic"},
    "VETJ": {"iata": "TEI", "name": "Tezu Airport", "city": "Tezu", "type": "Domestic"},
    "VETZ": {"iata": "TEZ", "name": "Tezpur Airport", "city": "Tezpur", "type": "Domestic"},
    "VEZO": {"iata": "ZER", "name": "Zero Airport", "city": "Zero", "type": "Domestic"},
    "VIAM": {"iata": "AMD", "name": "Sardar Vallabhbhai Patel International", "city": "Ahmedabad", "type": "Domestic"},
    "VIAR": {"iata": "ATQ", "name": "Sri Guru Ram Dass Jee International", "city": "Amritsar", "type": "Domestic"},
    "VIBK": {"iata": "BKB", "name": "Bikaner Airport", "city": "Bikaner", "type": "Domestic"},
    "VIBR": {"iata": "KUU", "name": "Kullu Manali Airport", "city": "Bhuntar", "type": "Domestic"},
    "VIBT": {"iata": "BUP", "name": "Bathinda Airport", "city": "Bathinda", "type": "Domestic"},
    "VICG": {"iata": "IXC", "name": "Chandigarh Airport", "city": "Chandigarh", "type": "Domestic"},
    "VIDD": {"iata": "DED", "name": "Dehradun Airport", "city": "Dehradun", "type": "Domestic"},
    "VIDN": {"iata": "DIB", "name": "Dibrugarh Airport", "city": "Dibrugarh", "type": "Domestic"},
    "VIHR": {"iata": "DHM", "name": "Kangra Airport", "city": "Dharamshala", "type": "Domestic"},
    "VIJN": {"iata": "JGB", "name": "Jagdalpur Airport", "city": "Jagdalpur", "type": "Domestic"},
    "VIJO": {"iata": "JDH", "name": "Jodhpur Airport", "city": "Jodhpur", "type": "Domestic"},
    "VIJP": {"iata": "JAI", "name": "Jaipur International", "city": "Jaipur", "type": "Domestic"},
    "VIJR": {"iata": "JSA", "name": "Jaisalmer Airport", "city": "Jaisalmer", "type": "Domestic"},
    "VIJU": {"iata": "IXJ", "name": "Jammu Airport", "city": "Jammu", "type": "Domestic"},
    "VIKA": {"iata": "KNU", "name": "Kanpur Airport", "city": "Kanpur", "type": "Domestic"},
    "VIKO": {"iata": "KTU", "name": "Kota Airport", "city": "Kota", "type": "Domestic"},
    "VILD": {"iata": "LUH", "name": "Ludhiana Airport", "city": "Ludhiana", "type": "Domestic"},
    "VILH": {"iata": "IXL", "name": "Leh Kushok Bakula Rimpochee Airport", "city": "Leh", "type": "Domestic"},
    "VILK": {"iata": "LUH", "name": "Ludhiana Airport", "city": "Ludhiana", "type": "Domestic"},
    "VIPK": {"iata": "IXP", "name": "Pathankot Airport", "city": "Pathankot", "type": "Domestic"},
    "VIPT": {"iata": "PGH", "name": "Pantnagar Airport", "city": "Pantnagar", "type": "Domestic"},
    "VISM": {"iata": "SLV", "name": "Shimla Airport", "city": "Shimla", "type": "Domestic"},
    "VISR": {"iata": "IXS", "name": "Silchar Airport", "city": "Silchar", "type": "Domestic"},
    "VIST": {"iata": "SXR", "name": "Sheikh ul-Alam International", "city": "Srinagar", "type": "Domestic"},
    "VITE": {"iata": "TNI", "name": "Satna Airport", "city": "Satna", "type": "Domestic"},
    "VITK": {"iata": "TKB", "name": "Tezu Airport", "city": "Tezu", "type": "Domestic"},
    "VIUD": {"iata": "UDR", "name": "Maharana Pratap Airport", "city": "Udaipur", "type": "Domestic"},
    "VIVA": {"iata": "VNS", "name": "Lal Bahadur Shastri Airport", "city": "Varanasi", "type": "Domestic"},
    "VOBI": {"iata": "BEP", "name": "Bellary Airport", "city": "Bellary", "type": "Domestic"},
    "VOBR": {"iata": "RJA", "name": "Rajahmundry Airport", "city": "Rajahmundry", "type": "Domestic"},
    "VOBZ": {"iata": "VGA", "name": "Vijayawada Airport", "city": "Vijayawada", "type": "Domestic"},
    "VOCB": {"iata": "CJB", "name": "Coimbatore International", "city": "Coimbatore", "type": "Domestic"},
    "VOCP": {"iata": "CDP", "name": "Kadapa Airport", "city": "Kadapa", "type": "Domestic"},
    "VODG": {"iata": "DGH", "name": "Deoghar Airport", "city": "Deoghar", "type": "Domestic"},
    "VOGO": {"iata": "GOI", "name": "Dabolim Airport", "city": "Goa", "type": "Domestic"},
    "VOHB": {"iata": "HBX", "name": "Hubli Airport", "city": "Hubli", "type": "Domestic"},
    "VOHS": {"iata": "HYD", "name": "Rajiv Gandhi International", "city": "Hyderabad", "type": "Domestic"},
    "VOMD": {"iata": "IXM", "name": "Madurai Airport", "city": "Madurai", "type": "Domestic"},
    "VOML": {"iata": "IXE", "name": "Mangalore International", "city": "Mangalore", "type": "Domestic"},
    "VOMM": {"iata": "MAA", "name": "Chennai International", "city": "Chennai", "type": "Domestic"},
    "VONS": {"iata": "ISK", "name": "Nashik Airport", "city": "Nashik", "type": "Domestic"},
    "VOPB": {"iata": "IXZ", "name": "Vir Savarkar International", "city": "Port Blair", "type": "Domestic"},
    "VOPC": {"iata": "PNY", "name": "Pondicherry Airport", "city": "Puducherry", "type": "Domestic"},
    "VOPN": {"iata": "PUT", "name": "Sri Sathya Sai Airport", "city": "Puttaparthi", "type": "Domestic"},
    "VORY": {"iata": "RJA", "name": "Rajahmundry Airport", "city": "Rajahmundry", "type": "Domestic"},
    "VOSM": {"iata": "SXV", "name": "Salem Airport", "city": "Salem", "type": "Domestic"},
    "VOTJ": {"iata": "TJV", "name": "Thanjavur Airport", "city": "Thanjavur", "type": "Domestic"},
    "VOTK": {"iata": "TCR", "name": "Tuticorin Airport", "city": "Thoothukudi", "type": "Domestic"},
    "VOTP": {"iata": "TIR", "name": "Tirupati Airport", "city": "Tirupati", "type": "Domestic"},
    "VOTR": {"iata": "TIR", "name": "Tirupati Airport", "city": "Tirupati", "type": "Domestic"},
    "VOTV": {"iata": "TRV", "name": "Trivandrum International", "city": "Thiruvananthapuram", "type": "Domestic"},
    "VOVR": {"iata": "RMD", "name": "Ramagundam Airport", "city": "Ramagundam", "type": "Domestic"},
    "VOWA": {"iata": "WGC", "name": "Warangal Airport", "city": "Warangal", "type": "Domestic"},
    "VOYK": {"iata": "YNK", "name": "Yelahanka Air Force Station", "city": "Bengaluru", "type": "Domestic"},
    "VQPR": {"iata": "PBH", "name": "Paro Airport (Bhutan)", "city": "Paro", "type": "International"},
}


# Helper functions
def get_airport_by_iata(iata_code):
    """Get airport details by IATA code"""
    return next((airport for airport in INDIAN_AIRPORTS.values() if airport["iata"] == iata_code), None)


def get_airport_by_icao(icao_code):
    """Get airport details by ICAO code"""
    return INDIAN_AIRPORTS.get(icao_code)


def get_all_airports(airport_type=None):
    """Get all airports, optionally filtered by type"""
    if airport_type:
        return {code: data for code, data in INDIAN_AIRPORTS.items() if data["type"] == airport_type}
    return INDIAN_AIRPORTS